service: app

provider:
    name: aws
    region: us-east-1

plugins:
    - ./vendor/bref/bref

functions:
    api:
        handler: index.php
        description: ''
        runtime: php-PHP_VERSION-fpm
        timeout: 30 # in seconds
        url: true

# Exclude files from deployment
package:
    patterns:
        - '!node_modules/**'
        - '!tests/**'
